package au.org.scoutmaster.help;

public enum HelpPageIdentifier
{
	BULK_DOWNLOAD, BUSINESS_MESSAGES, CALL_BACK_MANAGER,

	CALLER_ID, CAMPAIGN_ALLOCATIONS, CAMPAIGN_NUMBER_MODIFIER,

	CLEANSER_BILLING_HISTORY, CLEANSER_CONTROL_PANEL, DASHBOARD,

	ENCRYPTION_ACTIVATE, ENCRYPTION_CONSOLE, ENCRYPTION_DISCLAIMER_DETAILS, ENCRYPTION_PAGE_ONE,
	ENCRYPTION_RESTORE_KEYS_CONFIGURATION, ENCRYPTION_RESTORE_KEYS_DONE, ENCRYPTION_RESTORE_KEYS_PREAMBLE,
	ENCRYPTION_RESTORE_KEYS_UPLOAD, ENCRYPTION_RESTORE_WIZARD, ENCRYPTION_SETUP, ENCRYPTION_SETUP_CONFIGURATION,
	ENCRYPTION_SETUP_DISCLAIMER, ENCRYPTION_SETUP_DOWNLOAD, ENCRYPTION_SETUP_GENERATION, ENCRYPTION_SETUP_MIGRATION,
	ENCRYPTION_SETUP_PREAMBLE, ENCRYPTION_SETUP_READY, ENCRYPTION_SETUP_WIZARD, ENCRYPTION_USER_CHANGES,
	ENCRYPTION_USER_DONE, ENCRYPTION_USER_MANAGER_DOESNT_HAVE_KEY, ENCRYPTION_USER_NOT_CONFIGURED,
	ENCRYPTION_USER_REVIEW, ENCRYPTION_USER_SELECTION, ENCRYPTION_USERS_WIZARD,

	EXPORT, EXTERNAL_CONNECTION, INVALID_EXTENSION, LEAD_INJECTOR, LOGIN_MESSAGES, PREVIOUS_SESSION_TERMINATED,
	QUEUE_ROUTE_REPORT, RECORDING, ROUTE, ROUTESCRIPT, STEAL_EXTENSION, STEAL_EXTENSION_IN_USE, TRUNK, DID_MAP_ID,
	SYSTEM_SETTINGS, QUEUE_ROUTE_DETAILS_REPORT, CRM_LOGGERS, CDR_PER_TEAM_AGENT_DAILY_REPORT, TEAM_VIEW
}
